package com.applet.apply.mapper;

import com.applet.apply.entity.CouponInfo;
import com.applet.apply.entity.CouponInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CouponInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    long countByExample(CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    int deleteByExample(CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    int insert(CouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    int insertSelective(CouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    List<CouponInfo> selectByExample(CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    CouponInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") CouponInfo record, @Param("example") CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    int updateByExample(@Param("record") CouponInfo record, @Param("example") CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    int updateByPrimaryKeySelective(CouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    int updateByPrimaryKey(CouponInfo record);
}
