package com.applet.apply.mapper;

import com.applet.apply.entity.UserCoupon;
import com.applet.apply.entity.UserCouponExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    long countByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    int deleteByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    int insert(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    int insertSelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    List<UserCoupon> selectByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    UserCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    int updateByExample(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    int updateByPrimaryKeySelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    int updateByPrimaryKey(UserCoupon record);
}
