package com.applet.apply.mapper;

import com.applet.apply.entity.ViewUserCoupon;
import com.applet.apply.entity.ViewUserCouponExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ViewUserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    long countByExample(ViewUserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_coupon
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    List<ViewUserCoupon> selectByExample(ViewUserCouponExample example);
}
