package com.applet.apply.entity;

import com.applet.common.util.Constants;
import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * 优惠券信息类
 *
 */
public class CouponInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.user_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.coupon_name
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private String couponName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.coupon_type
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Integer couponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.gain_applet_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Integer gainAppletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.gain_price
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Double gainPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.use_applet_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Integer useAppletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.use_price
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Double usePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.denomination
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Double denomination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.make_issue_num
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Integer makeIssueNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.already_issue_num
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Integer alreadyIssueNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.activity_start
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = Constants.DATE_TIME_JDK)
    private Date activityStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.activity_over
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = Constants.DATE_TIME_JDK)
    private Date activityOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.create_time
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = Constants.DATE_TIME_JDK)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_info.status
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    private Integer status;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.id
     *
     * @return the value of coupon_info.id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.id
     *
     * @param id the value for coupon_info.id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.user_id
     *
     * @return the value of coupon_info.user_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.user_id
     *
     * @param userId the value for coupon_info.user_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.coupon_name
     *
     * @return the value of coupon_info.coupon_name
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.coupon_name
     *
     * @param couponName the value for coupon_info.coupon_name
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.coupon_type
     *
     * @return the value of coupon_info.coupon_type
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Integer getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.coupon_type
     *
     * @param couponType the value for coupon_info.coupon_type
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.gain_applet_id
     *
     * @return the value of coupon_info.gain_applet_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Integer getGainAppletId() {
        return gainAppletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.gain_applet_id
     *
     * @param gainAppletId the value for coupon_info.gain_applet_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setGainAppletId(Integer gainAppletId) {
        this.gainAppletId = gainAppletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.gain_price
     *
     * @return the value of coupon_info.gain_price
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Double getGainPrice() {
        return gainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.gain_price
     *
     * @param gainPrice the value for coupon_info.gain_price
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setGainPrice(Double gainPrice) {
        this.gainPrice = gainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.use_applet_id
     *
     * @return the value of coupon_info.use_applet_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Integer getUseAppletId() {
        return useAppletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.use_applet_id
     *
     * @param useAppletId the value for coupon_info.use_applet_id
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setUseAppletId(Integer useAppletId) {
        this.useAppletId = useAppletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.use_price
     *
     * @return the value of coupon_info.use_price
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Double getUsePrice() {
        return usePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.use_price
     *
     * @param usePrice the value for coupon_info.use_price
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setUsePrice(Double usePrice) {
        this.usePrice = usePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.denomination
     *
     * @return the value of coupon_info.denomination
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Double getDenomination() {
        return denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.denomination
     *
     * @param denomination the value for coupon_info.denomination
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setDenomination(Double denomination) {
        this.denomination = denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.make_issue_num
     *
     * @return the value of coupon_info.make_issue_num
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Integer getMakeIssueNum() {
        return makeIssueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.make_issue_num
     *
     * @param makeIssueNum the value for coupon_info.make_issue_num
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setMakeIssueNum(Integer makeIssueNum) {
        this.makeIssueNum = makeIssueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.already_issue_num
     *
     * @return the value of coupon_info.already_issue_num
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Integer getAlreadyIssueNum() {
        return alreadyIssueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.already_issue_num
     *
     * @param alreadyIssueNum the value for coupon_info.already_issue_num
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setAlreadyIssueNum(Integer alreadyIssueNum) {
        this.alreadyIssueNum = alreadyIssueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.activity_start
     *
     * @return the value of coupon_info.activity_start
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Date getActivityStart() {
        return activityStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.activity_start
     *
     * @param activityStart the value for coupon_info.activity_start
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setActivityStart(Date activityStart) {
        this.activityStart = activityStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.activity_over
     *
     * @return the value of coupon_info.activity_over
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Date getActivityOver() {
        return activityOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.activity_over
     *
     * @param activityOver the value for coupon_info.activity_over
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setActivityOver(Date activityOver) {
        this.activityOver = activityOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.create_time
     *
     * @return the value of coupon_info.create_time
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.create_time
     *
     * @param createTime the value for coupon_info.create_time
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_info.status
     *
     * @return the value of coupon_info.status
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_info.status
     *
     * @param status the value for coupon_info.status
     *
     * @mbg.generated Wed Jan 08 18:05:31 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

}
