package com.applet.apply.entity;

import com.applet.common.util.Constants;
import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class UserCoupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.user_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.coupon_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.gain_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = Constants.DATE_TIME_JDK)
    private Date gainTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.use_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = Constants.DATE_TIME_JDK)
    private Date useTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.status
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer status;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.id
     *
     * @return the value of user_coupon.id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.id
     *
     * @param id the value for user_coupon.id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.user_id
     *
     * @return the value of user_coupon.user_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.user_id
     *
     * @param userId the value for user_coupon.user_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.coupon_id
     *
     * @return the value of user_coupon.coupon_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.coupon_id
     *
     * @param couponId the value for user_coupon.coupon_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.gain_time
     *
     * @return the value of user_coupon.gain_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Date getGainTime() {
        return gainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.gain_time
     *
     * @param gainTime the value for user_coupon.gain_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setGainTime(Date gainTime) {
        this.gainTime = gainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.use_time
     *
     * @return the value of user_coupon.use_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.use_time
     *
     * @param useTime the value for user_coupon.use_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.status
     *
     * @return the value of user_coupon.status
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.status
     *
     * @param status the value for user_coupon.status
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public UserCoupon(Integer id, Integer status) {
        this.id = id;
        this.useTime = new Date();
        this.status = status;
    }
}
