package com.applet.apply.entity;

import com.applet.common.util.Constants;
import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class ViewUserCoupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.user_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.coupon_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.coupon_name
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private String couponName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.coupon_type
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer couponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.use_applet_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer useAppletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.use_applet_name
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private String useAppletName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.use_applet_logo
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private String useAppletLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.use_price
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Double usePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.denomination
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Double denomination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.gain_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = Constants.DATE_TIME_JDK)
    private Date gainTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.use_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = Constants.DATE_TIME_JDK)
    private Date useTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.activity_over
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = Constants.DATE_TIME_JDK)
    private Date activityOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user_coupon.status
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    private Integer status;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.id
     *
     * @return the value of view_user_coupon.id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.id
     *
     * @param id the value for view_user_coupon.id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.user_id
     *
     * @return the value of view_user_coupon.user_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.user_id
     *
     * @param userId the value for view_user_coupon.user_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.coupon_id
     *
     * @return the value of view_user_coupon.coupon_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.coupon_id
     *
     * @param couponId the value for view_user_coupon.coupon_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.coupon_name
     *
     * @return the value of view_user_coupon.coupon_name
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.coupon_name
     *
     * @param couponName the value for view_user_coupon.coupon_name
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.coupon_type
     *
     * @return the value of view_user_coupon.coupon_type
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.coupon_type
     *
     * @param couponType the value for view_user_coupon.coupon_type
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.use_applet_id
     *
     * @return the value of view_user_coupon.use_applet_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getUseAppletId() {
        return useAppletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.use_applet_id
     *
     * @param useAppletId the value for view_user_coupon.use_applet_id
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setUseAppletId(Integer useAppletId) {
        this.useAppletId = useAppletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.use_applet_name
     *
     * @return the value of view_user_coupon.use_applet_name
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public String getUseAppletName() {
        return useAppletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.use_applet_name
     *
     * @param useAppletName the value for view_user_coupon.use_applet_name
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setUseAppletName(String useAppletName) {
        this.useAppletName = useAppletName == null ? null : useAppletName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.use_applet_logo
     *
     * @return the value of view_user_coupon.use_applet_logo
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public String getUseAppletLogo() {
        return useAppletLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.use_applet_logo
     *
     * @param useAppletLogo the value for view_user_coupon.use_applet_logo
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setUseAppletLogo(String useAppletLogo) {
        this.useAppletLogo = useAppletLogo == null ? null : useAppletLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.use_price
     *
     * @return the value of view_user_coupon.use_price
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Double getUsePrice() {
        return usePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.use_price
     *
     * @param usePrice the value for view_user_coupon.use_price
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setUsePrice(Double usePrice) {
        this.usePrice = usePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.denomination
     *
     * @return the value of view_user_coupon.denomination
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Double getDenomination() {
        return denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.denomination
     *
     * @param denomination the value for view_user_coupon.denomination
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setDenomination(Double denomination) {
        this.denomination = denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.gain_time
     *
     * @return the value of view_user_coupon.gain_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Date getGainTime() {
        return gainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.gain_time
     *
     * @param gainTime the value for view_user_coupon.gain_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setGainTime(Date gainTime) {
        this.gainTime = gainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.use_time
     *
     * @return the value of view_user_coupon.use_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.use_time
     *
     * @param useTime the value for view_user_coupon.use_time
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.activity_over
     *
     * @return the value of view_user_coupon.activity_over
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Date getActivityOver() {
        return activityOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.activity_over
     *
     * @param activityOver the value for view_user_coupon.activity_over
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setActivityOver(Date activityOver) {
        this.activityOver = activityOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user_coupon.status
     *
     * @return the value of view_user_coupon.status
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user_coupon.status
     *
     * @param status the value for view_user_coupon.status
     *
     * @mbg.generated Wed Jan 08 18:21:04 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}
